---
- hosts: all
  become: yes
  tasks:
  - name: install webserver on ubuntu
    apt:
      name: apache2
      state: present
    when: ansible_os_family =="Debian"

  - name: start webserver on ubuntu
    apt:
      name: apache2
      state: started
    when: ansible_os_family =="Debian"

  - name: install webserver on linux
    yum:
      name: httpd      
      state: present
    when: ansible_os_family =="RedHat"

  - name: start webserver on linux
    yum:
      name: https
      state: started
    when: ansible_os_family =="RedHat" 

